### PR TITLE
Migrate static images to S3.

### PR DESCRIPTION
**Pull request by brotatos**
The old images setup was deemed overkill for what the website needed and we now
have the advantage of the Amazon's CDN.

Several images will still need to be modified via the production database as   
their links are manually hardcoded in there.

- [ ] change production db links to S3

### CODE REVIEW

**Comment by jhladky** [comment]
1. It's not necessary to change the domain, simply modify the static.calpolyieee.org record to be a CNAME to the amazon domain.
2. Is there a frontend interface for uploading pictures to S3 through the website?

**Comment by jhladky** [comment]
Sorry, reading the S3 documentation, it looks like I misunderstood the purpose of Flask-S3. For image uploads I think we want something more like this: https://aws.amazon.com/articles/1434

**Comment by brotatos** [comment]
Sounds good. An S3 console where users could see their own image links as well as upload additional ones will be terribly useful. Furthermore, it'd probably be handy to integrate this into the post UI as well.

As for the CNAME, I'm not sure if that's safe to do as we don't have the JS assets on the bucket yet and I noticed that some code refers to loading the JS and/or CSS from the VPS. Do we want to store both JS and CSS on the server as well?

**Comment by brotatos** [comment]
Taken care of in #347.

**Pull request closed without merging**
